import { Agent, Task, CommMessage, HITLItem, ActivityEvent, SessionMessage, MetricsData } from "./types"

export const mockAgents: Agent[] = [
  {
    id: "main",
    name: "Madbot",
    emoji: "🧠",
    status: "idle",
    model: "claude-opus-4",
    workspace: "~/.openclaw/workspace",
    tools: ["web_search", "browser", "exec", "read", "write", "message"],
    uptime: "3d 14h 22m",
    tokenUsage: 847203,
    tokenLimit: 2000000,
    sessionCount: 12,
    currentTask: undefined,
  },
  {
    id: "coder",
    name: "Codebot",
    emoji: "💻",
    status: "executing",
    model: "claude-opus-4",
    workspace: "~/.openclaw/workspace-coder",
    tools: ["exec", "read", "write", "edit", "web_search", "browser"],
    uptime: "1d 8h 45m",
    tokenUsage: 1245890,
    tokenLimit: 2000000,
    sessionCount: 8,
    currentTask: "Building Mission Control Dashboard",
  },
  {
    id: "researcher",
    name: "ResearchBot",
    emoji: "🔍",
    status: "reasoning",
    model: "claude-sonnet-4",
    workspace: "~/.openclaw/workspace-research",
    tools: ["web_search", "web_fetch", "read", "write"],
    uptime: "0d 6h 12m",
    tokenUsage: 324100,
    tokenLimit: 1000000,
    sessionCount: 3,
    currentTask: "Analyzing competitor landscape",
  },
  {
    id: "ops",
    name: "OpsBot",
    emoji: "⚙️",
    status: "idle",
    model: "claude-haiku-4",
    workspace: "~/.openclaw/workspace-ops",
    tools: ["exec", "read", "nodes"],
    uptime: "7d 2h 0m",
    tokenUsage: 156000,
    tokenLimit: 500000,
    sessionCount: 2,
  },
  {
    id: "writer",
    name: "WriteBot",
    emoji: "✍️",
    status: "errored",
    model: "claude-sonnet-4",
    workspace: "~/.openclaw/workspace-writer",
    tools: ["read", "write", "web_search"],
    uptime: "0d 0h 45m",
    tokenUsage: 89400,
    tokenLimit: 1000000,
    sessionCount: 1,
    currentTask: "Draft blog post — errored on API call",
  },
]

export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Build Mission Control Dashboard",
    description: "Create a centralized dashboard for managing the OpenClaw agent swarm with real-time status, kanban board, and HITL approval flows.",
    assignedAgent: "coder",
    priority: "high",
    column: "in-progress",
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(Date.now() - 300000),
    progress: 65,
    logs: ["Initialized Next.js project", "Installed dependencies", "Building dashboard components"],
    output: undefined,
  },
  {
    id: "t2",
    title: "Research competitor pricing models",
    description: "Analyze pricing strategies of top 10 AI agent platforms and create a comparison matrix.",
    assignedAgent: "researcher",
    priority: "medium",
    column: "in-progress",
    createdAt: new Date(Date.now() - 43200000),
    updatedAt: new Date(Date.now() - 600000),
    progress: 40,
    logs: ["Identified 10 competitors", "Scraped pricing pages", "Building comparison matrix"],
  },
  {
    id: "t3",
    title: "Set up monitoring alerts",
    description: "Configure system monitoring and alerting for all agent processes with Slack notifications.",
    assignedAgent: "ops",
    priority: "medium",
    column: "backlog",
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(Date.now() - 172800000),
    progress: 0,
    logs: [],
  },
  {
    id: "t4",
    title: "Write onboarding documentation",
    description: "Create comprehensive getting-started guide for new users of the OpenClaw platform.",
    assignedAgent: "writer",
    priority: "low",
    column: "pending-approval",
    createdAt: new Date(Date.now() - 259200000),
    updatedAt: new Date(Date.now() - 7200000),
    progress: 90,
    logs: ["Outlined structure", "Drafted 8 sections", "Added code examples", "Pending review"],
    output: "# Getting Started with OpenClaw\n\n## Installation\n```bash\nnpm install -g openclaw\n```\n\n## Quick Start\n...",
  },
  {
    id: "t5",
    title: "API rate limiter implementation",
    description: "Implement token bucket rate limiting for the Gateway API to prevent abuse.",
    assignedAgent: "coder",
    priority: "high",
    column: "backlog",
    createdAt: new Date(Date.now() - 3600000),
    updatedAt: new Date(Date.now() - 3600000),
    progress: 0,
    logs: [],
  },
  {
    id: "t6",
    title: "Deploy staging environment",
    description: "Set up staging environment on AWS with proper IAM roles and networking.",
    assignedAgent: "ops",
    priority: "urgent",
    column: "pending-approval",
    createdAt: new Date(Date.now() - 7200000),
    updatedAt: new Date(Date.now() - 1800000),
    progress: 80,
    logs: ["Created CloudFormation template", "IAM roles configured", "Awaiting approval for deployment"],
  },
  {
    id: "t7",
    title: "Refactor auth module",
    description: "Migrate from JWT to session-based auth with refresh tokens.",
    priority: "medium",
    column: "backlog",
    createdAt: new Date(Date.now() - 604800000),
    updatedAt: new Date(Date.now() - 604800000),
    progress: 0,
    logs: [],
  },
  {
    id: "t8",
    title: "Weekly metrics report",
    description: "Generate and send the weekly agent performance metrics report.",
    assignedAgent: "main",
    priority: "low",
    column: "done",
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(Date.now() - 86400000),
    progress: 100,
    logs: ["Collected metrics from all agents", "Generated charts", "Sent report to Slack"],
    output: "Weekly Report: 47 tasks completed, 1.2M tokens used, avg completion time 23min",
  },
]

export const mockCommMessages: CommMessage[] = [
  { id: "c1", sourceAgent: "🧠 Madbot", targetAgent: "💻 Codebot", summary: "Delegated: Build Mission Control Dashboard", timestamp: new Date(Date.now() - 86400000), type: "delegation" },
  { id: "c2", sourceAgent: "💻 Codebot", targetAgent: "🧠 Madbot", summary: "Progress update: 65% complete on dashboard", timestamp: new Date(Date.now() - 300000), type: "response" },
  { id: "c3", sourceAgent: "🧠 Madbot", targetAgent: "🔍 ResearchBot", summary: "Spawned for competitor analysis task", timestamp: new Date(Date.now() - 43200000), type: "spawn" },
  { id: "c4", sourceAgent: "🔍 ResearchBot", targetAgent: "🧠 Madbot", summary: "Found 10 competitors, analyzing pricing", timestamp: new Date(Date.now() - 600000), type: "response" },
  { id: "c5", sourceAgent: "🧠 Madbot", targetAgent: "✍️ WriteBot", summary: "Delegated: Write onboarding docs", timestamp: new Date(Date.now() - 259200000), type: "delegation" },
  { id: "c6", sourceAgent: "✍️ WriteBot", targetAgent: "🧠 Madbot", summary: "Error: API rate limit exceeded during research", timestamp: new Date(Date.now() - 7200000), type: "response" },
  { id: "c7", sourceAgent: "⚙️ OpsBot", targetAgent: "🧠 Madbot", summary: "Staging deploy ready, requesting approval", timestamp: new Date(Date.now() - 1800000), type: "response" },
]

export const mockHITLItems: HITLItem[] = [
  {
    id: "h1",
    agentId: "ops",
    agentName: "⚙️ OpsBot",
    action: "Deploy to staging environment (AWS us-east-1)",
    reason: "Deployment involves infrastructure changes that require human verification before applying.",
    context: "CloudFormation stack with 3 EC2 instances, RDS PostgreSQL, and ALB. Estimated cost: $450/mo.",
    priority: "urgent",
    timestamp: new Date(Date.now() - 1800000),
    status: "pending",
  },
  {
    id: "h2",
    agentId: "writer",
    agentName: "✍️ WriteBot",
    action: "Publish onboarding documentation to docs site",
    reason: "Content publication to public-facing site requires human review.",
    context: "8-section getting started guide with code examples. 2,400 words total.",
    priority: "medium",
    timestamp: new Date(Date.now() - 7200000),
    status: "pending",
  },
  {
    id: "h3",
    agentId: "coder",
    agentName: "💻 Codebot",
    action: "Delete legacy API routes (12 files)",
    reason: "Destructive file operation flagged for approval.",
    context: "Removing deprecated v1 API routes that have been replaced by v2. No active consumers found.",
    priority: "low",
    timestamp: new Date(Date.now() - 14400000),
    status: "pending",
  },
]

export const mockActivity: ActivityEvent[] = [
  { id: "a1", agentId: "coder", agentName: "Codebot", agentEmoji: "💻", action: "Wrote file", detail: "src/components/dashboard/AgentCards.tsx", timestamp: new Date(Date.now() - 120000) },
  { id: "a2", agentId: "researcher", agentName: "ResearchBot", agentEmoji: "🔍", action: "Web search", detail: "\"AI agent platform pricing 2025\"", timestamp: new Date(Date.now() - 300000) },
  { id: "a3", agentId: "coder", agentName: "Codebot", agentEmoji: "💻", action: "Executed", detail: "npm install recharts lucide-react", timestamp: new Date(Date.now() - 600000) },
  { id: "a4", agentId: "ops", agentName: "OpsBot", agentEmoji: "⚙️", action: "Requested approval", detail: "Deploy staging environment", timestamp: new Date(Date.now() - 1800000) },
  { id: "a5", agentId: "writer", agentName: "WriteBot", agentEmoji: "✍️", action: "Errored", detail: "API rate limit exceeded on web_fetch", timestamp: new Date(Date.now() - 7200000) },
  { id: "a6", agentId: "main", agentName: "Madbot", agentEmoji: "🧠", action: "Spawned agent", detail: "ResearchBot for competitor analysis", timestamp: new Date(Date.now() - 43200000) },
  { id: "a7", agentId: "main", agentName: "Madbot", agentEmoji: "🧠", action: "Delegated task", detail: "Mission Control Dashboard → Codebot", timestamp: new Date(Date.now() - 86400000) },
  { id: "a8", agentId: "coder", agentName: "Codebot", agentEmoji: "💻", action: "Read file", detail: "package.json", timestamp: new Date(Date.now() - 90000) },
  { id: "a9", agentId: "researcher", agentName: "ResearchBot", agentEmoji: "🔍", action: "Fetched URL", detail: "https://competitor.ai/pricing", timestamp: new Date(Date.now() - 450000) },
  { id: "a10", agentId: "coder", agentName: "Codebot", agentEmoji: "💻", action: "Wrote file", detail: "src/lib/mock-data.ts", timestamp: new Date(Date.now() - 60000) },
]

export const mockSessionMessages: SessionMessage[] = [
  { role: "user", content: "Build a Mission Control dashboard for managing the OpenClaw agent swarm.", timestamp: new Date(Date.now() - 86400000) },
  { role: "assistant", content: "I'll build the Mission Control dashboard. Let me start by initializing the Next.js project with TypeScript, Tailwind, and shadcn/ui.\n\n```bash\nnpx create-next-app@latest mission-control --typescript --tailwind\n```", timestamp: new Date(Date.now() - 86300000) },
  { role: "assistant", content: "Project initialized. Now installing additional dependencies:\n- recharts for charts\n- lucide-react for icons\n- @dnd-kit for drag and drop", timestamp: new Date(Date.now() - 86000000) },
  { role: "assistant", content: "Building the dashboard components now. Starting with the agent status overview cards...", timestamp: new Date(Date.now() - 85000000) },
]

export const mockMetrics: MetricsData[] = [
  { date: "Mon", tokens: 245000, tasks: 8, avgTime: 18 },
  { date: "Tue", tokens: 312000, tasks: 12, avgTime: 22 },
  { date: "Wed", tokens: 198000, tasks: 6, avgTime: 15 },
  { date: "Thu", tokens: 425000, tasks: 15, avgTime: 25 },
  { date: "Fri", tokens: 380000, tasks: 11, avgTime: 20 },
  { date: "Sat", tokens: 156000, tasks: 4, avgTime: 12 },
  { date: "Sun", tokens: 289000, tasks: 9, avgTime: 19 },
]
